### ISSUE TITLE
Sequel::DatabaseError: Mysql::Error: Data too long for column 'telephone' at row 102

### ISSUE THREAD

**Issue by krisdante** [DivanteLtd/anonymizer#11]
`Sequel::DatabaseError: Mysql::Error: Data too long for column 'telephone' at row 102` error is thrown when trying to anonymize Magento 2 database

**Comment by JJK96** [comment]
Maybe there should be an option to define the length

**Comment by mkoszut** [comment]
This issue is solved in this [commit](https://github.com/DivanteLtd/anonymizer/commit/a9d6980b6c646862a938535cd41f307585821e76). I changed phone number format.
