### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by Yihka** [DivanteLtd/anonymizer#43]
I'm having some trouble understanding how to configure the files. I simply want to:

1. Make a dump from the current local database.
2. Process the data of the local database.
3. Anonymize the data.
4. Save a (gzipped) .sql file somewhere.

---

I made a project file, called [database_name].json. I've configured this in multiple ways, currently like this:

```
{
    "type": "extended",
    "basic_type": "magento_1_9",
    "dump_server": {
        "host": "",
        "port": "",
        "user": "",
        "path": "/var/www/vhosts/anonymizer/dumps_to_dump/"
    }
}

```
I think it tries to read a .sql file from this directory called [database_name].sql.

Then I've made an environment file, called local.yml. I've configured it in multiple ways also. It is very unclear to me what this file is for.

```
logger:
  enabled: true
dump_server:
web_server:
database:
  user: admin
  host: localhost
  pass: xxx
tmp_path: /tmp
```
Now when I run the command

`RUBY_ENV=local bundle exec rake project:anonymize[database_name]` all it does is delete all my tables on the current local server and keep a table in it called 'fake_users'. No .sql files are created and the local database is basically destroyed.

What am I doing wrong? How does this tool work?

**Comment by mkoszutowski** [comment]
In general, it looks good. I suggest changing `logger: enabled: true` to `logger: enabled: false`. Why? Param `logger: enabled: true` is responsible for logging to file. Now all errors are logged to file in dir `log/`. When you change to `false` all errors will be displayed.

**Comment by Yihka** [comment]
Ah, that explains why I stopped seeing errors. Thanks!

The mistake I made was assuming it would read a .sql file. However, it tries to read a .sql.gz file. So changing this solves the issue.
